const data = {
  products: [
    {
      // _id: 1,
      brand:"羊牌",
      category: "類別",
      name: "鮭魚清肉1KG",
      slug: "salmon",
      price: 1000,
      description: "好吃的鮭魚",
      image: "product1.jpg",
      countInStock: 10,
      rating: 4,
      numReviews: 0,
    },
    {
      // _id: 2,
      brand:"羊頭牌",
      category: "類別",
      name: "干貝",
      slug: "salmon1",
      price: 300,
      description: "又大又嫩的干貝",
      image: "product2.jpg",
      countInStock: 5,
      rating: 5,
      numReviews: 0,
    },
    {
      // _id: 3,
      brand:"牛奶牌",
      category: "類別",
      name: "帆立貝",
      slug: "salmon2",
      price: 250,
      description: "天然去內臟帆立貝",
      image: "product3.jpg",
      countInStock: 10,
      rating: 4.5,
      numReviews: 0,
    },
    {
      // _id: 4,
      brand:"貓咪牌",
      category: "類別",
      name: "產品名稱",
      slug: "salmon3",
      price: 100,
      description: "產品描述",
      image: "product1.jpg",
      countInStock: 10,
      rating: 4.5,
      numReviews: 0,
    },
    {
      // _id: 5,
      brand:"豬牌",
      category: "類別",
      name: "大干貝",
      slug: "salmon4",
      price: 300,
      description: "產品描述",
      image: "product2.jpg",
      countInStock: 0,
      rating: 4.5,
      numReviews: 0,
    },
  ],
};

export default data;
